name: bun-linux
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TEST_TAG: bun-test'

on:
  push:
    branches: [main, bun-actions]
    paths:
      - "src/**/*"
      - "test/**/*"
      - "build.zig"
      - "Makefile"
      - "Dockerfile"
  pull_request:
    branches: [main]
    paths:
      - "src/**/*"
      - "test/**/*"
      - "build.zig"
      - "Makefile"
      - "Dockerfile"
  workflow_dispatch:

jobs:
  linux:
    name: ${{matrix.tag}}
    runs-on: ${{matrix.runner}}
    timeout-minutes: 90
    strategy:
      matrix:
        include:
          - cpu: haswell
            tag: linux-x64
            arch: x86_64
            build_arch: amd64
            runner: linux-amd64
          - cpu: westmere
            tag: linux-x64-baseline
            arch: x86_64
            build_arch: amd64
            runner: linux-amd64
          - cpu: native
            tag: linux-aarch64
            arch: aarch64
            build_arch: arm64
            runner: linux-arm64

    steps:
      - name: Build
        uses: oven-sh/bun/.github/actions/builds/linux@main
        env:
          cpu: ${{ matrix.cpu }}
          tag: ${{ matrix.tag }}
          arch: ${{ matrix.aarch }}
          build_arch: ${{ matrix.build_arch }}
          runner: ${{ matrix.runner }}
