name: bun-macOS-x64-baseline
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TEST_TAG: bun-test'

on:
  push:
    branches: [main, bun-actions]
    paths:
      - "src/**/*"
      - "test/**/*"
      - "build.zig"
      - "Makefile"
      - "Dockerfile"
  pull_request:
    branches: [main]
    paths:
      - "src/**/*"
      - "test/**/*"
      - "build.zig"
      - "Makefile"
      - "Dockerfile"
  workflow_dispatch:

jobs:
  macos-object-files:
    name: macOS Object
    runs-on: linux-amd64
    strategy:
      matrix:
        include:
          - cpu: westmere
            arch: x86_64
            tag: bun-obj-darwin-x64-baseline
    steps:
      - name: Object files
        uses: oven-sh/bun/.github/actions/builds/macos/object-files@master
        env:
          cpu: ${{ matrix.cpu }}
          arch: ${{ matrix.aarch }}
          tag: ${{ matrix.tag }}
  macOS-cpp:
    name: macOS C++
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 90
    strategy:
      matrix:
        include:
          - cpu: westmere
            arch: x86_64
            tag: bun-darwin-x64-baseline
            obj: bun-obj-darwin-x64-baseline
            runner: macos-11
            artifact: bun-obj-darwin-x64-baseline
            webkit_url: "https://github.com/oven-sh/WebKit/releases/download/latest/bun-webkit-macos-amd64-lto.tar.gz"
            dependencies: true
            compile_obj: false
          - cpu: westmere
            arch: x86_64
            tag: bun-darwin-x64-baseline
            obj: bun-obj-darwin-x64-baseline
            runner: macos-11
            artifact: bun-obj-darwin-x64-baseline
            webkit_url: "https://github.com/oven-sh/WebKit/releases/download/latest/bun-webkit-macos-amd64-lto.tar.gz"
            dependencies: false
            compile_obj: true
    steps:
      - name: C++
        uses: oven-sh/bun/.github/actions/builds/macos/cpp@master
        env:
          cpu: ${{ matrix.cpu }}
          arch: ${{ matrix.aarch }}
          tag: ${{ matrix.tag }}
          obj: ${{ matrix.obj }}
          artifact: ${{ matrix.artifact }}
          webkit_url: ${{ matrix.webkit_url }}
          runner: ${{ matrix.runner }}
          dependencies: ${{ matrix.dependencies }}
          compile_obj: ${{ matrix.compile_obj }}

  macOS:
    name: macOS Link
    runs-on: ${{ matrix.runner }}
    needs: [macOS-cpp, macos-object-files]
    timeout-minutes: 90
    strategy:
      matrix:
        include:
          - cpu: westmere
            arch: x86_64
            tag: bun-darwin-x64-baseline
            obj: bun-obj-darwin-x64-baseline
            package: bun-darwin-x64
            runner: macos-11
            artifact: bun-obj-darwin-x64-baseline
            webkit_url: "https://github.com/oven-sh/WebKit/releases/download/latest/bun-webkit-macos-amd64-lto.tar.gz"
    steps:
      - name: Link
        uses: oven-sh/bun/.github/actions/builds/macos/link@master
        env:
          cpu: ${{ matrix.cpu }}
          arch: ${{ matrix.aarch }}
          tag: ${{ matrix.tag }}
          obj: ${{ matrix.obj }}
          package: ${{ matrix.package }}
          artifact: ${{ matrix.artifact }}
          webkit_url: ${{ matrix.webkit_url }}
          runner: ${{ matrix.runner }}
