name: CI workflow for bun
on:
  push:
    branches: [main, bun-actions]
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: self-hosted
    container:
      image: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path:
      - name: Checkout submodules
        run: apt-get install git && git -c submodule."src/javascript/jsc/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Set tag var
        id: vars
        run: echo ::set-output name=docker_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}
      - name: Run build
        id: run
        run: |
          DOCKER_BUILDKIT=1 docker build --build-arg BUILDARCH=amd64 --build-arg GITHUB_WORKSPACE=${GITHUB_WORKSPACE} -t bun:${{steps.vars.outputs.docker_tag}} -f Dockerfile --tag=release --progress=plain . 
          DOCKER_BUILDKIT=1 docker push ghcr.io/jarred-sumner/bun:${{steps.vars.outputs.docker_tag}}
