name: bun
on:
  push:
    branches: [main, bun-actions]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TEST_TAG: bun-test'

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git -c submodule."src/javascript/jsc/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build release image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: build_release
          tags: jarred-sumner/bun-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=min

  tests:
    runs-on: self-hosted
    needs: setup
    strategy:
      matrix:
        image:
          [
            "test_create_next",
            "test_create_react",
            "test_bun_run",
            "test_hmr",
            "test_no_hmr",
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git -c submodule."src/javascript/jsc/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: ${{matrix.image}} - Run tests
        uses: docker/build-push-action@v2
        with:
          context: .
          target: ${{matrix.image}}
          tags: jarred-sumner/bun-${{matrix.image}}:latest
          cache-from: type=gha

  release:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    needs:
      - setup
      - tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git -c submodule."src/javascript/jsc/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: release
          tags: |
            jarred-sumner/bun:${GITHUB_REF}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=min
