name: bun
on:
  push:
    branches: [main, bun-actions]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TEST_TAG: bun-test'

jobs:
  tests:
    runs-on: self-hosted
    strategy:
      matrix:
        task:
          [
            "test-with-hmr",
            "test-no-hmr",
            "test-create-next",
            "test-create-react",
            "test-bun-run",
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git -c submodule."src/javascript/jsc/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Cache Builds
        id: cache-builds
        uses: actions/cache@v2
        with:
          path: bun-binary
          key: ${{ runner.os }}-${{ runner.arch }}-${{github.sha}}
      - name: Pull Base Image
        if: steps.cache-builds.outputs.cache-hit != 'true'
        run: docker pull bunbunbunbun/bun-base:latest && docker pull bunbunbunbun/bun-base-with-zig-and-webkit:latest && docker tag bun-base:latest bunbunbunbun/bun-base && docker tag bun-base-with-zig-and-webkit:latest bunbunbunbun/bun-base-with-zig-and-webkit:latest
      - name: Build Release Image
        uses: docker/build-push-action@v2
        if: steps.cache-builds.outputs.cache-hit != 'true'
        with:
          context: .
          target: release
          tags: bun:${{github.sha}}
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
          builder: ${{ steps.buildx.outputs.name }}
          load: true
      - name: Copy bun binary over to cache
        if: steps.cache-builds.outputs.cache-hit != 'true'
        env:
          CONTAINER_TAG: bun:${{github.sha}}
          BUN_RELEASE_DIR: /opt/bun
        run: bash .docker/copy-bun-binary.sh
      - name: ${{matrix.task}} - Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: test_base
          tags: jarred-sumner/bun-test:${{github.sha}}
          load: true
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
          builder: ${{ steps.buildx.outputs.name }}
      - name: ${{matrix.task}} - Run
        env:
          BUN_TEST_NAME: ${{matrix.task}}
          GITHUB_WORKSPACE: $GITHUB_WORKSPACE
        run: docker container run --security-opt seccomp=.docker/chrome.json --env GITHUB_WORKSPACE=$GITHUB_WORKSPACE --env BUN_TEST_NAME=$BUN_TEST_NAME --ulimit memlock=-1:-1 --init --rm jarred-sumner/bun-test:${{github.sha}}
  release:
    runs-on: self-hosted
    needs: tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git -c submodule."src/javascript/jsc/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build release image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: release
          tags: ghcr.io/jarred-sumner/bun:${{github.sha}}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
