name: bun
on:
  push:
    branches: [main, bun-actions]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TEST_TAG: bun-test'

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git -c submodule."src/javascript/jsc/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build release image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: release
          tags: jarred-sumner/bun:${{github.sha}}
          cache-from: type=gha
          cache-to: type=gha,mode=min

  tests:
    runs-on: self-hosted
    needs: setup
    strategy:
      matrix:
        task:
          [
            "test-with-hmr",
            "test-no-hmr",
            "test-create-next",
            "test-create-react",
            "test-bun-run",
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git -c submodule."src/javascript/jsc/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: ${{matrix.task}} - Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: test_base
          tags: jarred-sumner/bun-test_base:${{github.sha}}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=min
      - name: ${{matrix.task}} - Run
        run: |
          docker run --rm --init --ulimit memlock=-1:-1 jarred-sumner/bun-test_base:${{github.sha}} --env  BUN_TEST_NAME=${{matrix.task}} --env GITHUB_WORKSPACE=${GITHUB_WORKSPACE} run-test.sh

  release:
    runs-on: self-hosted
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - setup
      - tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git -c submodule."src/javascript/jsc/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: release
          tags: |
            jarred-sumner/bun:${{github.sha}}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=min
