name: CI workflow for bun
on:
  push:
    branches: [main, bun-actions]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TEST_TAG: bun-test'

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git -c submodule."src/javascript/jsc/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build release image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: build_release
          tags: jarred-sumner/bun-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=min
  integration-tests-hmr:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git -c submodule."src/javascript/jsc/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          target: test_hmr
          tag: test_hmr
          cache-from: type=gha
          cache-to: type=gha,mode=min
      - name: Run test image
        run: docker run --rm --init --ulimit memlock=-1:-1 test_hmr
  integration-tests-no-hmr:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git -c submodule."src/javascript/jsc/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          target: test_no_hmr
          tag: test_no_hmr
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=min
      - name: Run test image
        run: docker run --rm --init --ulimit memlock=-1:-1 test_no_hmr
  test_create_next:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git -c submodule."src/javascript/jsc/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          target: test_create_next
          tag: test_create_next
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=min
      - name: Run test image
        run: docker run --rm --init --ulimit memlock=-1:-1 test_create_next
  test_create_react:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git -c submodule."src/javascript/jsc/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          target: test_create_react
          tag: test_create_react
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=min
      - name: Run test image
        run: docker run --rm --init --ulimit memlock=-1:-1 test_create_react
  test_bun_run:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git -c submodule."src/javascript/jsc/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          target: test_bun_run
          tag: test_bun_run
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=min
      - name: Run test image
        run: docker run --rm --init --ulimit memlock=-1:-1 test_bun_run
  release:
    runs-on: self-hosted
    needs: |
      setup
      test_bun_run
      test_create_react
      test_create_next
      integration-tests-no-hmr
      integration-tests-hmr
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git -c submodule."src/javascript/jsc/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: release
          tags: |
            jarred-sumner/bun:${GITHUB_REF}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=min
